### ISSUE TITLE
Running gulp task test:unit returning an error

### ISSUE THREAD

**Issue by omguhh** [b091/ts-skeleton#13]
It used to work prior to the recent updates, but as of now every time I try to run the task I get an error like so : 
```
[10:30:21] 'test:unit' errored after 3.69 s
[10:30:21] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/..../test-ts-skeleton/ts-skeleton/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/..../test-ts-skeleton/ts-skeleton/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/...../test-ts-skeleton/ts-skeleton/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/...../test-ts-skeleton/ts-skeleton/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/..../test-ts-skeleton/ts-skeleton/node_modules/karma/lib/server.js:332:7)
    at Server.<anonymous> (/Users/...../test-ts-skeleton/ts-skeleton/node_modules/karma/lib/server.js:343:9)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:129:20)
    at net.js:1409:10
    at process._tickCallback (node.js:355:11)

Process finished with exit code 1
```

Any clue as to why? :squirrel:

**Comment by b091** [comment]
Hi,

what command do you run?
if it is `gulp test:unit` then this error may occur because there is no transpired code, so before it you should run `gulp compile`, or run `gulp test` which depends on `compile` task.
You can also make your IDE transpile code for you on save, then you can always run `gulp test:unit`

did i solve your problem?

**Comment by omguhh** [comment]
No, running  ```gulp compile  ``` /   ```gulp test  ``` did not solve the issue, the error remains the same. :(

**Comment by b091** [comment]
please try running:
```
npm install
```

```
gulp default
```

and if it doesn't work paste me the results.
